<?php

/* samples:

      1 => array(
         'name' => 'SampleCheckbox',
         'label' => 'Sample Checkbox',            // displayed before checkbox
         'post_label' => 'select this checkbox',  // displayed after checkbox
         'type' => 'integer',
         'input_type' => 'checkbox',
         'value' => 1,                            // value if checked
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
*/

$contests['default']['en_CA'] = array(
   'table_name' => 'hk_trek',
   'fields' => array(
      0 => array(
         'name' => 'ID',
         'label' => 'ID',
         'type' => 'integer',
         'primary_key' => 1,
      ),
      1 => array(
         'name' => 'Email',
         'label' => 'Email',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '255',
         'size' => '30',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      2 => array(
         'name' => 'FirstName',
         'label' => 'First Name',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '25',
         'size' => '25',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      3 => array(
         'name' => 'LastName',
         'label' => 'Last Name',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '25',
         'size' => '25',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      4 => array(
         'name' => 'Address',
         'label' => 'Address',
         'type' => 'string',
         'input_type' => 'textarea',
         'limit' => '',        // an empty limit indicates a text field
         'cols' => '30',
         'rows' => '2',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      5 => array(
         'name' => 'City',
         'label' => 'City',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '30',
         'size' => '30',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      6 => array(
         'name' => 'Province',
         'label' => 'Province',
         'type' => 'string',
         'input_type' => 'dropdown',
         'limit' => '30',
         'data' => array(
            ''   => '-- Select One --',
            'AB' => 'Alberta',
            'BC' => 'British Columbia',
            'MB' => 'Manitoba',
            'NB' => 'New Brunswick',
            'NL' => 'Newfoundland and Labrador',
            'NT' => 'Northwest Territories',
            'NS' => 'Nova Scotia',
            'NU' => 'Nunavut',
            'ON' => 'Ontario',
            'PE' => 'Prince Edward Island',
            'QC' => 'Qu&eacute;bec',
            'SK' => 'Saskatchewan',
            'YT' => 'Yukon'),
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      7 => array(
         'name' => 'Postal',
         'label' => 'Postal Code',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '10',
         'size' => '10',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      8 => array(
         'name' => 'Birthdate',
         'label' => 'Birth Date',
         'type' => 'date',
         'input_type' => 'date',
         'data' => array(
            'locale' => 'en_CA.utf8',
            'start_year' => 1908, 
            'end_year' => 1990,           // assuming minimum age is 18 years
            'empty_option' => TRUE,
            'all_empty' => ''),
         'default' => '',
         'null' => FALSE,
         'rules' => 'callback_check_date',
      ),
      9 => array(
         'name' => 'Gender',
         'label' => 'Gender',
         'type' => 'string',
         'input_type' => 'radio',
         'limit' => '1',
         'data' => array(
            'M' => 'Male', 
            'F' => 'Female'),
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      10 => array(
         'name' => 'Phone',
         'label' => 'Daytime Phone',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '14',
         'size' => '14',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      11 => array(
         'name' => 'submit',
         'label' => 'Enter Contest',
         'type' => 'submit',
         'input_type' => 'submit',
      ),
   ),
);

$contests['default']['fr_CA'] = array(
   'table_name' => 'hk_trek',
   'fields' => array(
      0 => array(
         'name' => 'ID',
         'label' => 'ID',
         'type' => 'integer',
         'primary_key' => 1,
      ),
      1 => array(
         'name' => 'Email',
         'label' => 'Courriel',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '255',
         'size' => '30',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      2 => array(
         'name' => 'FirstName',
         'label' => 'Pr&eacute;nom',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '25',
         'size' => '25',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      3 => array(
         'name' => 'LastName',
         'label' => 'Nom de famille',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '25',
         'size' => '25',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      4 => array(
         'name' => 'Address',
         'label' => 'Adresse<br />(rue, no, app.)',
         'type' => 'string',
         'input_type' => 'textarea',
         'limit' => '',        // an empty limit indicates a text field
         'cols' => '30',
         'rows' => '2',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      5 => array(
         'name' => 'City',
         'label' => 'Ville',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '30',
         'size' => '30',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      6 => array(
         'name' => 'Province',
         'label' => 'Province',
         'type' => 'string',
         'input_type' => 'dropdown',
         'limit' => '30',
         'data' => array(
            ''   => '-- cliquez et choisissez --',
            'AB' => 'Alberta',
            'BC' => 'Colombie-Britannique',
            'MB' => 'Manitoba',
            'NB' => 'Nouveau-Brunswick',
            'NL' => 'Terre-Neuve-et-Labrador',
            'NT' => 'Territoires du Nord-Ouest',
            'NS' => 'Nouvelle-&Eacute;cosse',
            'NU' => 'Nunavut',
            'ON' => 'Ontario',
            'PE' => '&Icirc;le-du-Prince-&Eacute;douard',
            'QC' => 'Qu&eacute;bec',
            'SK' => 'Saskatchewan',
            'YT' => 'Yukon'),
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      7 => array(
         'name' => 'Postal',
         'label' => 'Code postal',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '10',
         'size' => '10',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      8 => array(
         'name' => 'Birthdate',
         'label' => 'Date de naissance',
         'type' => 'date',
         'input_type' => 'date',
         'data' => array(
            'locale' => 'fr_CA.utf8',
            'start_year' => 1908, 
            'end_year' => 1990,           // assuming minimum age is 18 years
            'empty_option' => TRUE,
            'all_empty' => ''),
         'default' => '',
         'null' => FALSE,
         'rules' => 'callback_check_date',
      ),
      9 => array(
         'name' => 'Gender',
         'label' => 'Sexe',
         'type' => 'string',
         'input_type' => 'radio',
         'limit' => '1',
         'data' => array(
            'M' => 'M&acirc;le',
            'F' => 'Femelle'),
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      10 => array(
         'name' => 'Phone',
         'label' => 'Num&eacute;ro de t&eacute;l&eacute;phone',
         'type' => 'string',
         'input_type' => 'input',
         'limit' => '14',
         'size' => '14',
         'default' => '',
         'null' => FALSE,
         'rules' => 'trim|required',
      ),
      11 => array(
         'name' => 'submit',
         'label' => 'ENVOYER',
         'type' => 'submit',
         'input_type' => 'submit',
      ),
   ),
);

?>