#!/usr/local/bin/php

<?php

// -----------------------------------------------------------------------
// Script to autogenerate various coolbrew components
// -----------------------------------------------------------------------

$COOLBREW['command_line_interface'] = TRUE;
require_once 'coolbrew.inc.php';
get('coolbrew.generate.index', 'search');

?>